fulltag-demo: add error checking for ulimit and mmap count.
If the ulimit -n or the maximum number of mmap segments are too low, the
demo will fail to fully load and will crash. Add checking for that first,
crashing and informing the user on how to set the system parameters so
the demo will run.

diff --git a/sh/full-tag-site-demo b/sh/full-tag-site-demo
--- a/sh/full-tag-site-demo
+++ b/sh/full-tag-site-demo
@@ -32,6 +32,39 @@ if [ "$VALID_ARGUMENTS" != "0" ]; then
   usage
 fi
 
+# Both curl and plunder consume a ton of file descriptors and mmap segments, in
+# the current demo design. We must check that we have enough fds for all files,
+# and that we have a high enough max_map_count.
+
+# Set a minimum required limit
+MIN_LIMIT=55555
+
+# Get the current limit for the number of open files
+current_limit=$(ulimit -n)
+
+if [ "$current_limit" -lt "$MIN_LIMIT" ]; then
+  echo "Error: The current limit for the number of open files is too low ($current_limit)."
+  echo "Please increase the limit to at least $MIN_LIMIT by running the following command:"
+  echo "ulimit -n $MIN_LIMIT"
+  echo "Note: This change will only apply to the current shell session."
+  exit 1
+fi
+
+# Set a minimum required limit for max map count
+MIN_MAP_COUNT=2621440
+
+# Get the current value for vm.max_map_count
+current_map_count=$(sysctl -n vm.max_map_count)
+
+if [ "$current_map_count" -lt "$MIN_MAP_COUNT" ]; then
+  echo "Error: The current value for vm.max_map_count is too low ($current_map_count)."
+  echo "Please increase the value to at least $MIN_MAP_COUNT by running the following command:"
+  echo "sudo sysctl -w vm.max_map_count=$MIN_MAP_COUNT"
+  echo "To make the change permanent, add the following line to /etc/sysctl.conf:"
+  echo "vm.max_map_count=$MIN_MAP_COUNT"
+  exit 1
+fi
+
 echo "PARSED_ARGUMENTS is $PARSED_ARGUMENTS"
 eval set -- "$PARSED_ARGUMENTS"
 while :
@@ -178,6 +211,12 @@ upload_images_for_file () {
 
     # Upload files 50 at a time so we get some http connection reusage.
     curl $CURL_ARGS
+
+    # If we error, we have to hard stop this thread because otherwise we're
+    # going to spam the console to the point where noone can see what happened.
+    if [[ $? != 0 ]]; then
+        exit -1
+    fi
 }
 
 #
@@ -204,6 +243,9 @@ upload_pages () {
 
             echo "page-$i.json"
             curl -d @$FILE -H "Content-Type: application/json" -X POST "$url"
+            if [[ $? != 0 ]]; then
+                exit -1
+            fi
         fi
     done
 }
